display_name: ClipShare
generic_name: Cross-Platform Clipboard Sync
icon: assets/images/logo/logo.png
categories:
  - Utility
startup_notify: true
keywords:
  - Clipboard
  - Clipboard Manager
  - Copy Paste
  - History
  - Productivity
  - Utility
  - Snippet
  - Manager
  - Enhanced Clipboard
  - Paste History
#actions:
#  - name: Say Hi
#    label: say-hi
#    arguments:
#      - --say
#      - hi
#  - name: Say Bye
#    label: say-bye
#    arguments:
#      - --say
#      - bye

# 您可以指定要与您的应用捆绑的共享库
#
# fastforge 会自动检测您的应用所依赖的共享库，但您也可以在此处手动指定它们。
#
# 以下示例展示了如何将 libcurl 库与您的应用捆绑在一起
#
# include:
#   - libcurl.so.4